### ISSUE TITLE
Card click leads to example.com domain.

### ISSUE THREAD

**Issue by MaciejLisCK** [wekan/wekan-mongodb#7] opened 2018-03-09 21:54 UTC
When I host on local card click leads to example.com domain.
![image](https://user-images.githubusercontent.com/1531086/37231751-a81269a0-23ec-11e8-8c2c-11c98eb70dd0.png)

**Comment by pblvsk** [comment] 2018-03-22 07:41
@MaciejLisCK make sure you have edited ROOT_URL=http://example.com in the compose file.

**Comment by biji** [comment] 2018-04-04 08:15
Not a bug, should be closed

**Comment by pblvsk** [comment] 2018-04-10 06:45
@xet7 could you close this? User error.

**Closed** 2018-04-10 10:40 UTC
